# Generated by Django 3.2.20 on 2023-07-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('stock_status', models.BooleanField(default=True, verbose_name='Stok Durumu')),
                ('images', models.ImageField(upload_to='product_images/', verbose_name='Resimler')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stok Miktarı')),
            ],
            options={
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
