# Generated by Django 3.2.20 on 2023-07-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_auto_20230727_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=1, upload_to='product_images/', verbose_name='Resimler'),
            preserve_default=False,
        ),
    ]
